- name: Build and Tag Docker Image
  run: |
    REPO_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')  # Convert to lowercase
    docker build -t ghcr.io/$REPO_NAME/mcm-project:latest .
    docker tag ghcr.io/$REPO_NAME/mcm-project:latest ghcr.io/$REPO_NAME/mcm-project:${{ github.run_number }}

- name: Push Docker Image
  run: |
    REPO_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')  # Convert to lowercase
    docker push ghcr.io/$REPO_NAME/mcm-project:latest
    docker push ghcr.io/$REPO_NAME/mcm-project:${{ github.run_number }}
