name: Java CI/CD to Cloud Foundry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # Deploy only on push to main

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Cloud Foundry CLI (Latest Version)
        run: |
          sudo apt remove cf-cli -y || true # Remove old version if exists
          curl -fsSL https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo tee /usr/share/keyrings/cloudfoundry-keyring.asc > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/cloudfoundry-keyring.asc] https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt update
          sudo apt install -y cf8-cli
          cf --version # Verify installation

      - name: Authenticate to Cloud Foundry
        env:
          CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}

        run: |
          echo "$CF_CLIENT_ID" "$CF_CLIENT_SECRET"
          cf api https://api.cf.us10-001.hana.ondemand.com
          cf auth "$CF_CLIENT_ID" "$CF_CLIENT_SECRET" --client-credentials
          cf target -o "$CF_ORG" -s "$CF_SPACE"

      - name: Deploy to Cloud Foundry
        run: cf push
