name: Java CI and Deploy to Cloud Foundry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Deploy only on push to main

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Cloud Foundry CLI
        run: |
          curl -fsSL https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo tee /usr/share/keyrings/cloudfoundry-keyring.asc > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/cloudfoundry-keyring.asc] https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt update
          sudo apt install -y cf-cli
          cf --version  # Verify installation

      - name: Login to Cloud Foundry using Service Key
        run: |
          echo '${{ secrets.CF_SERVICE_KEY }}' > service-key.json
          cf api https://api.cf.us10-001.hana.ondemand.com
          cf auth $(jq -r '.clientid' service-key.json) $(jq -r '.clientsecret' service-key.json) --client-credentials
          cf target -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}

      - name: Deploy to Cloud Foundry
        run: cf push
