name: Advanced CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Store Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar

  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: target/

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          REPO_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')  # Convert to lowercase
          docker build -t ghcr.io/$REPO_NAME/mcm-project:latest .
          docker tag ghcr.io/$REPO_NAME/mcm-project:latest ghcr.io/$REPO_NAME/mcm-project:${{ github.run_number }}

      - name: Push Docker Image
        run: |
          REPO_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')  # Convert to lowercase
          docker push ghcr.io/$REPO_NAME/mcm-project:latest
          docker push ghcr.io/$REPO_NAME/mcm-project:${{ github.run_number }}
